/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ControleTelaIngredientes;
import Model.Pedido;
import javax.swing.ImageIcon;

/**
 *
 * @author Diagramar
 */
public class TelaIngredientes extends javax.swing.JFrame {
    ImageIcon prato = new ImageIcon(getClass().getResource("/Imagens/botao_penne.png"));
    /**
     * Creates new form TelaMassas
     */
    ControleTelaIngredientes novo = new ControleTelaIngredientes(this);
    
    public TelaIngredientes(Pedido s) {
        initComponents();
        novo.setPedido(s);
        proximo.setEnabled(false);
        
    }
    public void botoes(){
        op1.setText(novo.inserePadrao(0));
        op2.setText(novo.inserePadrao(1));
        op3.setText(novo.inserePadrao(2));
        op4.setText(novo.inserePadrao(3));
        op5.setText(novo.inserePadrao(4));
        op6.setText(novo.inserePadrao(5));
        op7.setText(novo.inserePadrao(6));
        op8.setText(novo.inserePadrao(7));
        ope1.setText(novo.insereExtra(0));
        ope2.setText(novo.insereExtra(1));
        ope3.setText(novo.insereExtra(2));
        ope4.setText(novo.insereExtra(3));
    }
    public void desativar(){
        alcaparra.setEnabled(false);
        alho.setEnabled(false);
        alhoPoro.setEnabled(false);
        azeitona.setEnabled(false);        
        bacon.setEnabled(false);
        brocolis.setEnabled(false);
        camarao.setEnabled(false);
        carneSol.setEnabled(false);
        cebola.setEnabled(false);
        cenoura.setEnabled(false);
        champignon.setEnabled(false);
        ervilha.setEnabled(false);
        frango.setEnabled(false);
        gorgonzola.setEnabled(false);
        linguica.setEnabled(false);        
        milho.setEnabled(false);
        mussarela.setEnabled(false);
        palmito.setEnabled(false);
        peitoPeru.setEnabled(false);
        presunto.setEnabled(false);
        salmao.setEnabled(false);
        tomateSeco.setEnabled(false);
        uvaPassa.setEnabled(false);
        ovoCodorna.setEnabled(false);
        coalho.setEnabled(false);
        minas.setEnabled(false);        
        proximo.setEnabled(true);
    }
    public void ativar(){
        alcaparra.setEnabled(true);
        alho.setEnabled(true);
        alhoPoro.setEnabled(true);
        azeitona.setEnabled(true);        
        bacon.setEnabled(true);
        brocolis.setEnabled(true);
        camarao.setEnabled(true);
        carneSol.setEnabled(true);
        cebola.setEnabled(true);
        cenoura.setEnabled(true);
        champignon.setEnabled(true);
        ervilha.setEnabled(true);
        frango.setEnabled(true);
        gorgonzola.setEnabled(true);
        linguica.setEnabled(true);        
        milho.setEnabled(true);
        mussarela.setEnabled(true);
        palmito.setEnabled(true);
        peitoPeru.setEnabled(true);
        presunto.setEnabled(true);
        salmao.setEnabled(true);
        tomateSeco.setEnabled(true);
        uvaPassa.setEnabled(true);
        ovoCodorna.setEnabled(true);
        coalho.setEnabled(true);
        minas.setEnabled(true);            
        proximo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        proximo = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        op1 = new javax.swing.JButton();
        op2 = new javax.swing.JButton();
        op6 = new javax.swing.JButton();
        op3 = new javax.swing.JButton();
        op4 = new javax.swing.JButton();
        op5 = new javax.swing.JButton();
        op8 = new javax.swing.JButton();
        op7 = new javax.swing.JButton();
        ope3 = new javax.swing.JButton();
        ope2 = new javax.swing.JButton();
        ope1 = new javax.swing.JButton();
        ope4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sim = new javax.swing.JRadioButton();
        nao = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        alcaparra = new javax.swing.JButton();
        azeitona = new javax.swing.JButton();
        brocolis = new javax.swing.JButton();
        bacon = new javax.swing.JButton();
        cebola = new javax.swing.JButton();
        cenoura = new javax.swing.JButton();
        alhoPoro = new javax.swing.JButton();
        carneSol = new javax.swing.JButton();
        ervilha = new javax.swing.JButton();
        alho = new javax.swing.JButton();
        frango = new javax.swing.JButton();
        camarao = new javax.swing.JButton();
        presunto = new javax.swing.JButton();
        peitoPeru = new javax.swing.JButton();
        palmito = new javax.swing.JButton();
        salmao = new javax.swing.JButton();
        linguica = new javax.swing.JButton();
        mussarela = new javax.swing.JButton();
        milho = new javax.swing.JButton();
        gorgonzola = new javax.swing.JButton();
        champignon = new javax.swing.JButton();
        tomateSeco = new javax.swing.JButton();
        uvaPassa = new javax.swing.JButton();
        minas = new javax.swing.JButton();
        coalho = new javax.swing.JButton();
        ovoCodorna = new javax.swing.JButton();
        tomate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 224, 182));

        jPanel2.setBackground(new java.awt.Color(252, 207, 132));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sua(s) Escolha(s) :");

        proximo.setBackground(new java.awt.Color(252, 207, 132));
        proximo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        proximo.setText("Próximo");
        proximo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        voltar.setBackground(new java.awt.Color(252, 207, 132));
        voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(252, 207, 132));
        cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        op1.setBackground(new java.awt.Color(245, 156, 97));

        op2.setBackground(new java.awt.Color(245, 156, 97));

        op6.setBackground(new java.awt.Color(245, 156, 97));

        op3.setBackground(new java.awt.Color(245, 156, 97));

        op4.setBackground(new java.awt.Color(245, 156, 97));

        op5.setBackground(new java.awt.Color(245, 156, 97));

        op8.setBackground(new java.awt.Color(245, 156, 97));

        op7.setBackground(new java.awt.Color(245, 156, 97));

        ope3.setBackground(new java.awt.Color(245, 156, 97));
        ope3.setEnabled(false);

        ope2.setBackground(new java.awt.Color(245, 156, 97));
        ope2.setEnabled(false);

        ope1.setBackground(new java.awt.Color(245, 156, 97));
        ope1.setEnabled(false);

        ope4.setBackground(new java.awt.Color(245, 156, 97));
        ope4.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Adicionar Ingredientes Extras :");

        buttonGroup2.add(sim);
        sim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sim.setText("Sim");
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });

        buttonGroup2.add(nao);
        nao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nao.setText("Não");
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(op5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(op6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(op7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(op8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ope1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ope2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ope3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ope4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sim)
                                .addGap(18, 18, 18)
                                .addComponent(nao))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(sim)
                    .addComponent(nao))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ope3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ope2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ope4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ope1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/titulo_ingrediente.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(247, 224, 182));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        alcaparra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_alcaparra.png"))); // NOI18N
        alcaparra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcaparraActionPerformed(evt);
            }
        });

        azeitona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_azeitona.png"))); // NOI18N
        azeitona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azeitonaActionPerformed(evt);
            }
        });

        brocolis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_brocolis.png"))); // NOI18N
        brocolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brocolisActionPerformed(evt);
            }
        });

        bacon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_bacon.png"))); // NOI18N
        bacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconActionPerformed(evt);
            }
        });

        cebola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_cebola.png"))); // NOI18N
        cebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cebolaActionPerformed(evt);
            }
        });

        cenoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_cenoura.png"))); // NOI18N
        cenoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenouraActionPerformed(evt);
            }
        });

        alhoPoro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_alho_poro.png"))); // NOI18N
        alhoPoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alhoPoroActionPerformed(evt);
            }
        });

        carneSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_carne_sol.png"))); // NOI18N
        carneSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneSolActionPerformed(evt);
            }
        });

        ervilha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_ervilha.png"))); // NOI18N

        alho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_alho.png"))); // NOI18N
        alho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alhoActionPerformed(evt);
            }
        });

        frango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_frango.png"))); // NOI18N
        frango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frangoActionPerformed(evt);
            }
        });

        camarao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_camarao.png"))); // NOI18N
        camarao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraoActionPerformed(evt);
            }
        });

        presunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_presunto.png"))); // NOI18N
        presunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presuntoActionPerformed(evt);
            }
        });

        peitoPeru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_peru.png"))); // NOI18N
        peitoPeru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peitoPeruActionPerformed(evt);
            }
        });

        palmito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_palmito.png"))); // NOI18N
        palmito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palmitoActionPerformed(evt);
            }
        });

        salmao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_salmao.png"))); // NOI18N
        salmao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salmaoActionPerformed(evt);
            }
        });

        linguica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_linguica.png"))); // NOI18N
        linguica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linguicaActionPerformed(evt);
            }
        });

        mussarela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_mussarela.png"))); // NOI18N
        mussarela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mussarelaActionPerformed(evt);
            }
        });

        milho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_milho.png"))); // NOI18N
        milho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milhoActionPerformed(evt);
            }
        });

        gorgonzola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_gorgonzola.png"))); // NOI18N
        gorgonzola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorgonzolaActionPerformed(evt);
            }
        });

        champignon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_champignon.png"))); // NOI18N
        champignon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champignonActionPerformed(evt);
            }
        });

        tomateSeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_tomate_seco.png"))); // NOI18N
        tomateSeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomateSecoActionPerformed(evt);
            }
        });

        uvaPassa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_uva.png"))); // NOI18N
        uvaPassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvaPassaActionPerformed(evt);
            }
        });

        minas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_minas.png"))); // NOI18N
        minas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minasActionPerformed(evt);
            }
        });

        coalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_coalho.png"))); // NOI18N
        coalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coalhoActionPerformed(evt);
            }
        });

        ovoCodorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_codorna.png"))); // NOI18N
        ovoCodorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovoCodornaActionPerformed(evt);
            }
        });

        tomate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_tomate.png"))); // NOI18N
        tomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(alcaparra, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alhoPoro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(azeitona, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bacon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brocolis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(camarao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carneSol, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cebola, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cenoura, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(ervilha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frango, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gorgonzola, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linguica, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(milho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mussarela, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(palmito, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peitoPeru, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(presunto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salmao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(champignon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tomateSeco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(uvaPassa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tomate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ovoCodorna, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coalho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alhoPoro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(azeitona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bacon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brocolis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(camarao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alcaparra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carneSol)
                            .addComponent(cebola)
                            .addComponent(cenoura)))
                    .addComponent(champignon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ervilha)
                    .addComponent(frango)
                    .addComponent(salmao)
                    .addComponent(presunto)
                    .addComponent(peitoPeru)
                    .addComponent(palmito)
                    .addComponent(mussarela)
                    .addComponent(milho)
                    .addComponent(linguica)
                    .addComponent(gorgonzola)
                    .addComponent(tomateSeco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uvaPassa)
                    .addComponent(tomate)
                    .addComponent(ovoCodorna)
                    .addComponent(coalho)
                    .addComponent(minas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alcaparraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcaparraActionPerformed
        novo.ingredientes_padrao("Alcaparra");
        novo.ingredientes_extra("Alcaparra", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_alcaparraActionPerformed

    private void azeitonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azeitonaActionPerformed
        novo.ingredientes_padrao("Azeitona");
        novo.ingredientes_extra("Azeitona", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_azeitonaActionPerformed

    private void brocolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brocolisActionPerformed
        novo.ingredientes_padrao("Brócolis");
        novo.ingredientes_extra("Brócolis", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_brocolisActionPerformed

    private void baconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconActionPerformed
        novo.ingredientes_padrao("Bacon");
        novo.ingredientes_extra("Bacon", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_baconActionPerformed

    private void cebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cebolaActionPerformed
        novo.ingredientes_padrao("Cebola");
        novo.ingredientes_extra("Cebola", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_cebolaActionPerformed

    private void cenouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenouraActionPerformed
        novo.ingredientes_padrao("Cenoura");
        novo.ingredientes_extra("Cenoura", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_cenouraActionPerformed

    private void alhoPoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alhoPoroActionPerformed
        novo.ingredientes_padrao("Alho Poró");
        novo.ingredientes_extra("Alho Poró", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_alhoPoroActionPerformed

    private void carneSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneSolActionPerformed
        novo.ingredientes_padrao("Carne de Sol");
        novo.ingredientes_extra("Carne de Sol", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_carneSolActionPerformed

    private void alhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alhoActionPerformed
        novo.ingredientes_padrao("Alho");
        novo.ingredientes_extra("Alho", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_alhoActionPerformed

    private void frangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frangoActionPerformed
        novo.ingredientes_padrao("Frango");
        novo.ingredientes_extra("Frango", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_frangoActionPerformed

    private void camaraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraoActionPerformed
        novo.ingredientes_padrao("Camarão");
        novo.ingredientes_extra("Camarão", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_camaraoActionPerformed

    private void presuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presuntoActionPerformed
        novo.ingredientes_padrao("Presunto");
        novo.ingredientes_extra("Presunto", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_presuntoActionPerformed

    private void peitoPeruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peitoPeruActionPerformed
        novo.ingredientes_padrao("Peito de Peru");
        novo.ingredientes_extra("Peito de Peru", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_peitoPeruActionPerformed

    private void palmitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palmitoActionPerformed
        novo.ingredientes_padrao("Palmito");
        novo.ingredientes_extra("Palmito", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_palmitoActionPerformed

    private void salmaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salmaoActionPerformed
        novo.ingredientes_padrao("Salmão");
        novo.ingredientes_extra("Salmão", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_salmaoActionPerformed

    private void linguicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linguicaActionPerformed
        novo.ingredientes_padrao("Linguiça Calabresa");
        novo.ingredientes_extra("Linguiça Calabresa", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_linguicaActionPerformed

    private void mussarelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mussarelaActionPerformed
        novo.ingredientes_padrao("Mussarela");
        novo.ingredientes_extra("Mussarela", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_mussarelaActionPerformed

    private void milhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milhoActionPerformed
        novo.ingredientes_padrao("Milho");
        novo.ingredientes_extra("Milho", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_milhoActionPerformed

    private void gorgonzolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorgonzolaActionPerformed
        novo.ingredientes_padrao("Gorgonzola");
        novo.ingredientes_extra("Gorgonzola", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_gorgonzolaActionPerformed

    private void champignonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champignonActionPerformed
        novo.ingredientes_padrao("Champignon");
        novo.ingredientes_extra("Champignon", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_champignonActionPerformed

    private void tomateSecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomateSecoActionPerformed
        novo.ingredientes_padrao("Tomate Seco");
        novo.ingredientes_extra("Tomate Seco", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_tomateSecoActionPerformed

    private void uvaPassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvaPassaActionPerformed
        novo.ingredientes_padrao("Uva Passa");
        novo.ingredientes_extra("Uva Passa", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_uvaPassaActionPerformed

    private void minasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minasActionPerformed
        novo.ingredientes_padrao("Queijo Minas");
        novo.ingredientes_extra("Queijo Minas", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_minasActionPerformed

    private void coalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coalhoActionPerformed
        novo.ingredientes_padrao("Queijo Coalho");
        novo.ingredientes_extra("Queijo Coalho", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_coalhoActionPerformed

    private void ovoCodornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovoCodornaActionPerformed
        novo.ingredientes_padrao("Ovo de Codorna");
        novo.ingredientes_extra("Ovo de Codorna", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_ovoCodornaActionPerformed

    private void tomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomateActionPerformed
        novo.ingredientes_padrao("Tomate");
        novo.ingredientes_extra("Tomate", sim.isEnabled());
        botoes();
    }//GEN-LAST:event_tomateActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        novo.proximo();
    }//GEN-LAST:event_proximoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        novo.voltar();
    }//GEN-LAST:event_voltarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        novo.cancelar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed
        
    }//GEN-LAST:event_simActionPerformed

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alcaparra;
    private javax.swing.JButton alho;
    private javax.swing.JButton alhoPoro;
    private javax.swing.JButton azeitona;
    private javax.swing.JButton bacon;
    private javax.swing.JButton brocolis;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton camarao;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton carneSol;
    private javax.swing.JButton cebola;
    private javax.swing.JButton cenoura;
    private javax.swing.JButton champignon;
    private javax.swing.JButton coalho;
    private javax.swing.JButton ervilha;
    private javax.swing.JButton frango;
    private javax.swing.JButton gorgonzola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton linguica;
    private javax.swing.JButton milho;
    private javax.swing.JButton minas;
    private javax.swing.JButton mussarela;
    private javax.swing.JRadioButton nao;
    private javax.swing.JButton op1;
    private javax.swing.JButton op2;
    private javax.swing.JButton op3;
    private javax.swing.JButton op4;
    private javax.swing.JButton op5;
    private javax.swing.JButton op6;
    private javax.swing.JButton op7;
    private javax.swing.JButton op8;
    private javax.swing.JButton ope1;
    private javax.swing.JButton ope2;
    private javax.swing.JButton ope3;
    private javax.swing.JButton ope4;
    private javax.swing.JButton ovoCodorna;
    private javax.swing.JButton palmito;
    private javax.swing.JButton peitoPeru;
    private javax.swing.JButton presunto;
    private javax.swing.JButton proximo;
    private javax.swing.JButton salmao;
    private javax.swing.JRadioButton sim;
    private javax.swing.JButton tomate;
    private javax.swing.JButton tomateSeco;
    private javax.swing.JButton uvaPassa;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
