/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Pedido;
import javax.swing.ImageIcon;

/**
 *
 * @author Diagramar
 */
public class TelaIngredientes extends javax.swing.JFrame {
    ImageIcon prato = new ImageIcon(getClass().getResource("/Imagens/botao_penne.png"));
    /**
     * Creates new form TelaMassas
     */
    public TelaIngredientes(Pedido s) {
        initComponents();
    }
    
    public void desativar(){
        alcaparra.setEnabled(false);
        alho.setEnabled(false);
        alhoPoro.setEnabled(false);
        azeitona.setEnabled(false);        
        bacon.setEnabled(false);
        brocolis.setEnabled(false);
        camarao.setEnabled(false);
        carneSol.setEnabled(false);
        cebola.setEnabled(false);
        cenoura.setEnabled(false);
        champignon.setEnabled(false);
        ervilha.setEnabled(false);
        frango.setEnabled(false);
        gorgonzola.setEnabled(false);
        linguica.setEnabled(false);        
        milho.setEnabled(false);
        mussarela.setEnabled(false);
        palmito.setEnabled(false);
        peitoPeru.setEnabled(false);
        presunto.setEnabled(false);
        salmao.setEnabled(false);
        tomateSeco.setEnabled(false);
        uvaPassa.setEnabled(false);
        ovoCodorna.setEnabled(false);
        coalho.setEnabled(false);
        minas.setEnabled(false);        
        proximo.setEnabled(true);
    }
    public void ativar(){
        alcaparra.setEnabled(true);
        alho.setEnabled(true);
        alhoPoro.setEnabled(true);
        azeitona.setEnabled(true);        
        bacon.setEnabled(true);
        brocolis.setEnabled(true);
        camarao.setEnabled(true);
        carneSol.setEnabled(true);
        cebola.setEnabled(true);
        cenoura.setEnabled(true);
        champignon.setEnabled(true);
        ervilha.setEnabled(true);
        frango.setEnabled(true);
        gorgonzola.setEnabled(true);
        linguica.setEnabled(true);        
        milho.setEnabled(true);
        mussarela.setEnabled(true);
        palmito.setEnabled(true);
        peitoPeru.setEnabled(true);
        presunto.setEnabled(true);
        salmao.setEnabled(true);
        tomateSeco.setEnabled(true);
        uvaPassa.setEnabled(true);
        ovoCodorna.setEnabled(true);
        coalho.setEnabled(true);
        minas.setEnabled(true);            
        proximo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        proximo = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        alcaparra = new javax.swing.JButton();
        azeitona = new javax.swing.JButton();
        brocolis = new javax.swing.JButton();
        bacon = new javax.swing.JButton();
        cebola = new javax.swing.JButton();
        cenoura = new javax.swing.JButton();
        alhoPoro = new javax.swing.JButton();
        carneSol = new javax.swing.JButton();
        ervilha = new javax.swing.JButton();
        alho = new javax.swing.JButton();
        frango = new javax.swing.JButton();
        camarao = new javax.swing.JButton();
        presunto = new javax.swing.JButton();
        peitoPeru = new javax.swing.JButton();
        palmito = new javax.swing.JButton();
        salmao = new javax.swing.JButton();
        linguica = new javax.swing.JButton();
        mussarela = new javax.swing.JButton();
        milho = new javax.swing.JButton();
        gorgonzola = new javax.swing.JButton();
        champignon = new javax.swing.JButton();
        tomateSeco = new javax.swing.JButton();
        uvaPassa = new javax.swing.JButton();
        minas = new javax.swing.JButton();
        coalho = new javax.swing.JButton();
        ovoCodorna = new javax.swing.JButton();
        tomate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 224, 182));

        jPanel2.setBackground(new java.awt.Color(252, 207, 132));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sua(s) Escolha(s) :");

        proximo.setBackground(new java.awt.Color(252, 207, 132));
        proximo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        proximo.setText("Próximo");
        proximo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        voltar.setBackground(new java.awt.Color(252, 207, 132));
        voltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cancelar.setBackground(new java.awt.Color(252, 207, 132));
        cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton39.setBackground(new java.awt.Color(245, 156, 97));

        jButton40.setBackground(new java.awt.Color(245, 156, 97));

        jButton41.setBackground(new java.awt.Color(245, 156, 97));

        jButton42.setBackground(new java.awt.Color(245, 156, 97));

        jButton43.setBackground(new java.awt.Color(245, 156, 97));

        jButton44.setBackground(new java.awt.Color(245, 156, 97));

        jButton45.setBackground(new java.awt.Color(245, 156, 97));

        jButton46.setBackground(new java.awt.Color(245, 156, 97));

        jButton47.setBackground(new java.awt.Color(245, 156, 97));
        jButton47.setEnabled(false);

        jButton48.setBackground(new java.awt.Color(245, 156, 97));
        jButton48.setEnabled(false);

        jButton49.setBackground(new java.awt.Color(245, 156, 97));
        jButton49.setEnabled(false);

        jButton50.setBackground(new java.awt.Color(245, 156, 97));
        jButton50.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Adicionar Ingredientes Extras :");

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Sim");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Não");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)))))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/titulo_ingrediente.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(247, 224, 182));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        alcaparra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_alcaparra.png"))); // NOI18N
        alcaparra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alcaparraActionPerformed(evt);
            }
        });

        azeitona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_azeitona.png"))); // NOI18N
        azeitona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azeitonaActionPerformed(evt);
            }
        });

        brocolis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_brocolis.png"))); // NOI18N
        brocolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brocolisActionPerformed(evt);
            }
        });

        bacon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_bacon.png"))); // NOI18N
        bacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconActionPerformed(evt);
            }
        });

        cebola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_cebola.png"))); // NOI18N
        cebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cebolaActionPerformed(evt);
            }
        });

        cenoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_cenoura.png"))); // NOI18N
        cenoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenouraActionPerformed(evt);
            }
        });

        alhoPoro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_alho_poro.png"))); // NOI18N
        alhoPoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alhoPoroActionPerformed(evt);
            }
        });

        carneSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_carne_sol.png"))); // NOI18N
        carneSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneSolActionPerformed(evt);
            }
        });

        ervilha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_ervilha.png"))); // NOI18N

        alho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_alho.png"))); // NOI18N
        alho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alhoActionPerformed(evt);
            }
        });

        frango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_frango.png"))); // NOI18N
        frango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frangoActionPerformed(evt);
            }
        });

        camarao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_camarao.png"))); // NOI18N
        camarao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraoActionPerformed(evt);
            }
        });

        presunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_presunto.png"))); // NOI18N
        presunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presuntoActionPerformed(evt);
            }
        });

        peitoPeru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_peru.png"))); // NOI18N
        peitoPeru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peitoPeruActionPerformed(evt);
            }
        });

        palmito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_palmito.png"))); // NOI18N
        palmito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palmitoActionPerformed(evt);
            }
        });

        salmao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_salmao.png"))); // NOI18N
        salmao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salmaoActionPerformed(evt);
            }
        });

        linguica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_linguica.png"))); // NOI18N
        linguica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linguicaActionPerformed(evt);
            }
        });

        mussarela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_mussarela.png"))); // NOI18N
        mussarela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mussarelaActionPerformed(evt);
            }
        });

        milho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_milho.png"))); // NOI18N
        milho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milhoActionPerformed(evt);
            }
        });

        gorgonzola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_gorgonzola.png"))); // NOI18N
        gorgonzola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorgonzolaActionPerformed(evt);
            }
        });

        champignon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_champignon.png"))); // NOI18N
        champignon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champignonActionPerformed(evt);
            }
        });

        tomateSeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_tomate_seco.png"))); // NOI18N
        tomateSeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomateSecoActionPerformed(evt);
            }
        });

        uvaPassa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_uva.png"))); // NOI18N
        uvaPassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvaPassaActionPerformed(evt);
            }
        });

        minas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_minas.png"))); // NOI18N
        minas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minasActionPerformed(evt);
            }
        });

        coalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_coalho.png"))); // NOI18N
        coalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coalhoActionPerformed(evt);
            }
        });

        ovoCodorna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_codorna.png"))); // NOI18N
        ovoCodorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovoCodornaActionPerformed(evt);
            }
        });

        tomate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao_tomate.png"))); // NOI18N
        tomate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(alcaparra, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alhoPoro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(azeitona, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bacon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brocolis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(camarao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carneSol, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cebola, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cenoura, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(ervilha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frango, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gorgonzola, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linguica, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(milho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mussarela, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(palmito, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peitoPeru, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(presunto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salmao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(champignon, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tomateSeco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(uvaPassa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tomate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ovoCodorna, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coalho, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alhoPoro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(azeitona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bacon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brocolis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(camarao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alcaparra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carneSol)
                            .addComponent(cebola)
                            .addComponent(cenoura)))
                    .addComponent(champignon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ervilha)
                    .addComponent(frango)
                    .addComponent(salmao)
                    .addComponent(presunto)
                    .addComponent(peitoPeru)
                    .addComponent(palmito)
                    .addComponent(mussarela)
                    .addComponent(milho)
                    .addComponent(linguica)
                    .addComponent(gorgonzola)
                    .addComponent(tomateSeco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uvaPassa)
                    .addComponent(tomate)
                    .addComponent(ovoCodorna)
                    .addComponent(coalho)
                    .addComponent(minas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alcaparraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alcaparraActionPerformed
        // TODO add your handling code here:
        //jButton13.setIcon(prato);
        jButton39.setText("Cappelletti de Queijo com Presunto");
    }//GEN-LAST:event_alcaparraActionPerformed

    private void azeitonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azeitonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_azeitonaActionPerformed

    private void brocolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brocolisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brocolisActionPerformed

    private void baconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baconActionPerformed

    private void cebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cebolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cebolaActionPerformed

    private void cenouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenouraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cenouraActionPerformed

    private void alhoPoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alhoPoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alhoPoroActionPerformed

    private void carneSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carneSolActionPerformed

    private void alhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alhoActionPerformed

    private void frangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frangoActionPerformed

    private void camaraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camaraoActionPerformed

    private void presuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presuntoActionPerformed

    private void peitoPeruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peitoPeruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peitoPeruActionPerformed

    private void palmitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palmitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palmitoActionPerformed

    private void salmaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salmaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salmaoActionPerformed

    private void linguicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linguicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linguicaActionPerformed

    private void mussarelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mussarelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mussarelaActionPerformed

    private void milhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milhoActionPerformed

    private void gorgonzolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorgonzolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gorgonzolaActionPerformed

    private void champignonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champignonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champignonActionPerformed

    private void tomateSecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomateSecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomateSecoActionPerformed

    private void uvaPassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvaPassaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uvaPassaActionPerformed

    private void minasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minasActionPerformed

    private void coalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coalhoActionPerformed

    private void ovoCodornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovoCodornaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ovoCodornaActionPerformed

    private void tomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tomateActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        // TODO add your handling code here:
        TelaExtras TelaExtras = new TelaExtras(new Pedido());
        TelaExtras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_proximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alcaparra;
    private javax.swing.JButton alho;
    private javax.swing.JButton alhoPoro;
    private javax.swing.JButton azeitona;
    private javax.swing.JButton bacon;
    private javax.swing.JButton brocolis;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton camarao;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton carneSol;
    private javax.swing.JButton cebola;
    private javax.swing.JButton cenoura;
    private javax.swing.JButton champignon;
    private javax.swing.JButton coalho;
    private javax.swing.JButton ervilha;
    private javax.swing.JButton frango;
    private javax.swing.JButton gorgonzola;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton linguica;
    private javax.swing.JButton milho;
    private javax.swing.JButton minas;
    private javax.swing.JButton mussarela;
    private javax.swing.JButton ovoCodorna;
    private javax.swing.JButton palmito;
    private javax.swing.JButton peitoPeru;
    private javax.swing.JButton presunto;
    private javax.swing.JButton proximo;
    private javax.swing.JButton salmao;
    private javax.swing.JButton tomate;
    private javax.swing.JButton tomateSeco;
    private javax.swing.JButton uvaPassa;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
