/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ControleTelaAtendente;
import Model.Pedido;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author labccet
 */
public class TelaAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendente
     */
    private ControleTelaAtendente ControleTelaAtendente;    
     int qtdPedidos = 0;
     private GridLayout layout;
     private Container container;
     
    public TelaAtendente() {      
                   
        initComponents();
        ControleTelaAtendente = new ControleTelaAtendente(this);
        layout = new GridLayout();
	container = getContentPane();
        PanelPedidos.setLayout(layout);        
        PanelPedidos.setPreferredSize(new Dimension(1000,500));                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        estoque = new javax.swing.JButton();
        relatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelPedidos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Atendente");
        setResizable(false);

        PanelTitulo.setBackground(new java.awt.Color(247, 207, 132));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setText("PEDIDOS");

        estoque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_estoque.png"))); // NOI18N
        estoque.setText("ESTOQUE");
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });

        relatorio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        relatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_relatorio.png"))); // NOI18N
        relatorio.setText("RELATÓRIO");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(estoque)
                .addGap(18, 18, 18)
                .addComponent(relatorio)
                .addGap(52, 52, 52))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setBackground(new java.awt.Color(247, 207, 132));
        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        PanelPedidos.setBackground(new java.awt.Color(247, 207, 182));

        javax.swing.GroupLayout PanelPedidosLayout = new javax.swing.GroupLayout(PanelPedidos);
        PanelPedidos.setLayout(PanelPedidosLayout);
        PanelPedidosLayout.setHorizontalGroup(
            PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PanelPedidosLayout.setVerticalGroup(
            PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ControleTelaAtendente getControle(){
        return ControleTelaAtendente;
    }
    public ControleTelaAtendente getControleAtendente(){
        return ControleTelaAtendente;
    }
    public void AdicionarPedidos(Pedido pedido){
        PanelPedido PanelPedido = new PanelPedido(this);
        PanelPedido.setTextPedido("PRODUTOS: \n");
        for(int i = 0; i < pedido.getPratos().size(); i++){
            String produto = pedido.getPratos().get(i).getNome() + "\n";
            PanelPedido.setTextPedido(produto);
        }            
        PanelPedido.setSenha(Integer.toString(pedido.getSenha()));
        PanelPedidos.add(PanelPedido);
        Dimension d = PanelPedidos.getPreferredSize();
        d.setSize(d.getWidth()+ 100,d.getHeight());
        PanelPedidos.setPreferredSize(d);
        this.setVisible(false);
        this.setVisible(true);        
    }
    public void retirarPedido(PanelPedido panel){
        PanelPedidos.remove(panel);
        Dimension d = PanelPedidos.getPreferredSize();
        d.setSize(d.getWidth()- 100,d.getHeight());
        PanelPedidos.setPreferredSize(d);
        this.setVisible(false);
        this.setVisible(true);
    }
    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
      TelaEstoque TelaEstoque = new TelaEstoque(this);
      TelaEstoque.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_estoqueActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // TODO add your handling code here:
        TelaSenhaGerente senha = new TelaSenhaGerente(this);
        senha.setVisible(true);
    }//GEN-LAST:event_relatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPedidos;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JButton estoque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton relatorio;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
